CREATE TABLE files (
    id SERIAL PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    "MIME type" VARCHAR(50),
    "Key" VARCHAR(255) NOT NULL,
    "URL" TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO files (file_name, "MIME type", "Key", "URL") VALUES
('user_icon_1.jpg', 'image/jpeg', 'Development/user_icon_1.xls', 'https://example.com/files/Development/user_icon_1.xls'),
('user_icon_2.jpg', 'image/jpeg', 'Finance/user_icon_2.pdf', 'https://example.com/files/Finance/user_icon_2.pdf'),
('user_icon_3.jpg', 'image/jpeg', 'Private/user_icon_3.pdf', 'https://example.com/files/Private/user_icon_3.pdf'),
('user_icon_4.jpg', 'image/jpeg', 'Public/user_icon_4.xls', 'https://example.com/files/Public/user_icon_4.xls'),
('user_icon_5.jpg', 'image/jpeg', 'Documents/user_icon_5.pdf', 'https://example.com/files/Documents/user_icon_5.pdf'),
('user_icon_6.jpg', 'image/jpeg', 'Development/user_icon_6.xls', 'https://example.com/files/Development/user_icon_6.xls'),
('user_icon_7.jpg', 'image/jpeg', 'Finance/user_icon_7.pdf', 'https://example.com/files/Finance/user_icon_7.pdf'),
('user_icon_8.jpg', 'image/jpeg', 'Private/user_icon_8.pdf', 'https://example.com/files/Private/user_icon_8.pdf'),
('user_icon_9.jpg', 'image/jpeg', 'Public/user_icon_9.xls', 'https://example.com/files/Public/user_icon_9.xls'),
('user_icon_10.jpg', 'image/jpeg', 'Documents/user_icon_10.pdf', 'https://example.com/files/Documents/user_icon_10.pdf'),
('director_photo_1.jpg', 'image/jpeg', 'Development/director_photo_1.pdf', 'https://example.com/files/Development/director_photo_1.pdf'),
('director_photo_2.jpg', 'image/jpeg', 'Finance/director_photo_2.pdf', 'https://example.com/files/Finance/director_photo_2.pdf'),
('director_photo_3.jpg', 'image/jpeg', 'Private/director_photo_3.xls', 'https://example.com/files/Private/director_photo_3.xls'),
('director_photo_4.jpg', 'image/jpeg', 'Public/director_photo_4.pdf', 'https://example.com/files/Public/director_photo_4.pdf'),
('director_photo_5.jpg', 'image/jpeg', 'Documents/director_photo_5.xls', 'https://example.com/files/Documents/director_photo_5.xls'),
('director_photo_6.jpg', 'image/jpeg', 'Development/director_photo_6.pdf', 'https://example.com/files/Development/director_photo_6.pdf'),
('director_photo_7.jpg', 'image/jpeg', 'Finance/director_photo_7.xls', 'https://example.com/files/Finance/director_photo_7.xls'),
('director_photo_8.jpg', 'image/jpeg', 'Private/director_photo_8.pdf', 'https://example.com/files/Private/director_photo_8.pdf'),
('director_photo_9.jpg', 'image/jpeg', 'Public/director_photo_9.xls', 'https://example.com/files/Public/director_photo_9.xls'),
('director_photo_10.jpg', 'image/jpeg', 'Documents/director_photo_10.pdf', 'https://example.com/files/Documents/director_photo_10.pdf'),
('poster_1.jpg', 'image/jpeg', 'Development/poster_1.xls', 'https://example.com/files/Development/poster_1.xls'),
('poster_2.jpg', 'image/jpeg', 'Finance/poster_2.pdf', 'https://example.com/files/Finance/poster_2.pdf'),
('poster_3.jpg', 'image/jpeg', 'Private/poster_3.pdf', 'https://example.com/files/Private/poster_3.pdf'),
('poster_4.jpg', 'image/jpeg', 'Public/poster_4.xls', 'https://example.com/files/Public/poster_4.xls'),
('poster_5.jpg', 'image/jpeg', 'Documents/poster_5.pdf', 'https://example.com/files/Documents/poster_5.pdf'),
('poster_6.jpg', 'image/jpeg', 'Development/poster_6.xls', 'https://example.com/files/Development/poster_6.xls'),
('poster_7.jpg', 'image/jpeg', 'Finance/poster_7.pdf', 'https://example.com/files/Finance/poster_7.pdf'),
('poster_8.jpg', 'image/jpeg', 'Private/poster_8.pdf', 'https://example.com/files/Private/poster_8.pdf'),
('poster_9.jpg', 'image/jpeg', 'Public/poster_9.xls', 'https://example.com/files/Public/poster_9.xls'),
('poster_10.jpg', 'image/jpeg', 'Documents/poster_10.pdf', 'https://example.com/files/Documents/poster_10.pdf');
